import type { Metadata } from "next";
import { hina } from "./../utils/font";
import './style/globals.css';
import Header from "./_components/header";

export const metadata: Metadata = {
  title: "嵐風くう 公式HP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={hina.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
